apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: tiledb
  namespace: tiledb-cloud
spec:
  mariaDbRef:
    name: tile-mariadb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    - "CREATE"
    - "INDEX"
    - "ALTER"
    - "DELETE"
    # - "ALL PRIVILEGES"
  database: "tiledb_rest"
  table: "*"
  username: tiledb
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
