apiVersion: k8s.mariadb.com/v1alpha1
kind: Grant
metadata:
  name: grant
  namespace: tiledb-cloud
spec:
  mariaDbRef:
    name: tiledb
  privileges:
    - "SELECT"
    - "INSERT"
    - "UPDATE"
    # - "ALL PRIVILEGES"
  database: "tiledb"
  table: "*"
  username: tiledb
  grantOption: true
  host: "%"
  requeueInterval: 30s
  retryInterval: 5s
